### ISSUE TITLE
CDN points to wrong version

### ISSUE THREAD

**Issue by aerni** [rumkin/favicon-switcher#2]
First, thanks for this amazing little script. It seems that this CDN link is still loading and older version than 1.2.0. It would be great if this were fixed.

```html
<script src="https://unpkg.com/favicon-switcher@1.2.0/dist/index.js" crossorigin="anonymous" type="application/javascript"></script>
```

**Comment by rumkin** [comment]
Thanks for reporting! Fixed this with version [1.2.2](https://unpkg.com/favicon-switcher@1.2.2/dist/index.js).
